### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by generateui** [keggsmurph21/CatOnline#1]
Hi! Always nice to see someone else making a cool implementation :). What about https://github.com/generateui/jsettlers-web (by me). Could we join forces and make something nice?

**Comment by keggsmurph21** [comment]
Hi @generateui ,

I appreciate the message and the support!  However, I think I want to continue to develop my project solo: I started it so that I could get a fuller grasp on the full stack of web development.  Although working on a team would definitely produce more robust results more quickly, that's not really my goal with this project.

Good luck with jsettlers2 and jsettlers-web!

Best,
Kevin
